spring:
  application:
    name: security-service
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://127.0.0.1:5440/security_service_db
    username: ${DB_USER:ETA_DBUser}
    password: ${DB_PASSWORD:devpassword123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: 127.0.0.1
    port: 5680
    username: ${RABBITMQ_USER:service-user}
    password: ${RABBITMQ_PASS:servicepassword}
    virtual-host: universal-host
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3

app:
  oauth2:
    redirect-uri: "http://localhost:8100/api/v0/login/oauth2/code/{registrationId}"
  default-admin:
    email: ${DEFAULT_ADMIN_EMAIL:admin@email.nl}
    password: ${DEFAULT_ADMIN_PASSWORD:123456nl}

server:
  port: 8101
  forward-headers-strategy: native

jwt:
  secret:
    access: ${JWT_SECRET_ACCESS:dGhpcy1pcy1hLWxvY2FsLWRldi1zZWNsLyZXQtYmFzZsLTY0LWtleQ==}

cookie:
  secure:
    state: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    root: INFO
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

token:
  activation:
    activate:
      ttl: 15
    resend:
      ttl: 15
  password:
    reset:
      ttl: 5

email:
  send:
    cooldown: 5

account:
  locked:
    cooldown: 5